# fuzzing 总开关
isFuzzNode: false
# 单个fuzz开关
  # consensus_tbft_impl
sendProposeStateFuzz: true
procProposeFuzz: true
commitBlockFuzz: true
delInvalidTxsFuzz: true
enterPrevoteFuzz: true
enterPrecommitFuzz: true
  # status_broadcaster
sendStateFuzz: true
sendRoundQCFuzz: true
sendPrecommitInStateFuzz: true
sendPrevoteInStateFuzz: true
sendProposalInStateFuzz: true
sendPrecommitOfRoundFuzz: true
sendPrevoteOfRoundFuzz: true
sendProposalOfRoundFuzz: true
# reserved option
othersFuzz: true
# delay开关
delay: false
delayBase: 0
delayLim: 10
