# fuzzing 总开关
isFuzzNode: false
# 单个fuzz开关
  # impl
sendProposeStateFuzz: false
procProposeFuzz: true
commitBlockFuzz: true
delInvalidTxsFuzz: false
enterPrevoteFuzz: true
enterPrecommitFuzz: true
  # status_broadcaster
sendStateFuzz: true
sendRoundQCFuzz: true
othersFuzz: true
# delay开关
delay: true
delayBase: 0
delayLim: 10